### PR TITLE
Add support to serialize JsonResult from MVC Actions

### PR DESCRIPTION
**Pull request by nirvinm**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Hello @nirvinm is this PR ready for review?

**Comment by nirvinm** [comment]
@MangelMaxime I hope so.

**Comment by nirvinm** [comment]
Is there any updates/comments on this PR?

**Comment by MangelMaxime** [comment]
Hello, sorry for the delay, how do you run the tests? 

I also get some deprecation warning when compiling the project about the lines:

```fs
httpContext
        .SetupSet(fun ctx -> ctx.Response.StatusCode)
```

I think `ThothJsonOptions` is missing some option because user can't provide it's extraCoder, removeEmpty option etc.

**Comment by nirvinm** [comment]
@MangelMaxime You can use `dotnet test` to run the unit tests.

I'll look at the deprecation warning. I thought of adding more ThothJsonOptions once we are done with basic integration with Asp.Net Core.

**Comment by MangelMaxime** [comment]
Ok thank you for the command `dotnet test`, I will update the `build.fsx` file to be able to runs the tests on the CI etc.

**Pull request closed without merging**
